#include <stdio.h>
#include <stdlib.h>
#include "../deploy/models/sleep_stage/sleep_stage_detector.h"

int main() {
    // Allocate our input tensor matching the [60][20] shape the C header expects
    float input_tensor[1][20][60];
    float output_logits[1][4] = {0.0f, 0.0f, 0.0f, 0.0f};

    // Load the raw binary generated by Python
    FILE *file = fopen("../outputs/dummy_sleep_input.bin", "rb");
    if (!file) {
        printf("Error: Could not open dummy_sleep_input.bin\n");
        return 1;
    }
    
    fread(input_tensor, sizeof(float), 1200, file);
    fclose(file);

    // Execute the isolated C model 
    sleep_stage_entry(input_tensor, output_logits);

    // Print results out to match Python's terminal format
    printf("--- Compiled C Model Logits ---\n");
    printf("Wake:        %.6f\n", output_logits[0][0]);
    printf("Light Sleep: %.6f\n", output_logits[0][1]);
    printf("Deep Sleep:  %.6f\n", output_logits[0][2]);
    printf("REM:         %.6f\n", output_logits[0][3]);

    return 0;
}