// This file is computer-generated by onnx2c 
// Command Line: onnx2c models/sleep_stage_mlp/sleep_state_tiny_conv_int8.onnx

// onnx2c
// Git Branch: master
// Git Commit: bfd0753

// ONNX Model
// Produced By: onnx.quantize, version 0.1.0
// ONNX IR version: 13

#include <float.h>
#include <math.h>
#include <stdbool.h>
#include <stdint.h>
#include <string.h>
#include <stdlib.h>

#define MAX(X,Y) ( X > Y ? X : Y)
#define MIN(X,Y) ( X < Y ? X : Y)
#define CLIP(X,L) ( MAX(MIN(X,L), -L) )

#if __STDC_VERSION__ < 199901L
#define FUNC_PREFIX
#else
#define FUNC_PREFIX static inline
#endif

static const int8_t tensor__Transpose_output_0_zero_point = 
-41;
static const float tensor__Transpose_output_0_scale = 
0.04183927178382873535f;
static const int8_t tensor_onnx__Conv_30_zero_point = 
0;
static const float tensor_onnx__Conv_30_scale = 
0.00333167659118771553f;
static const int8_t tensor_onnx__Conv_30_quantized[16][30][3] = 
{
  {
    {11, 2, 9},
    {8, 10, 1},
    {30, -42, -25},
    {36, -5, -31},
    {-19, -19, 37},
    {-30, 11, 24},
    {64, 127, 45},
    {23, 63, 25},
    {-81, -65, -59},
    {-15, -27, -10},
    {-20, -26, 31},
    {14, -9, -8},
    {-12, 20, 4},
    {-32, -23, 26},
    {-27, 7, -4},
    {-1, 17, -26},
    {2, -69, -79},
    {20, -27, -36},
    {62, 9, 12},
    {59, 43, 37},
    {4, 10, -2},
    {32, -14, -4},
    {-4, 12, 7},
    {-21, -9, -1},
    {-44, 28, -3},
    {2, 11, 22},
    {36, 46, -73},
    {17, 12, -24},
    {-18, -43, 1},
    {3, 21, 33}
  },
  {
    {6, 0, -14},
    {-12, -5, 3},
    {9, -9, 4},
    {14, -10, -19},
    {15, -4, -10},
    {10, 3, -33},
    {15, -5, 2},
    {15, -9, -13},
    {9, -6, 9},
    {25, -14, -4},
    {34, 20, 4},
    {29, 15, 18},
    {4, 14, 22},
    {-11, 7, 14},
    {13, 35, 36},
    {-12, 32, 30},
    {3, 27, 28},
    {4, 13, 34},
    {7, 3, 21},
    {-17, 0, 9},
    {-38, -6, -10},
    {-22, -12, -21},
    {2, -16, -9},
    {-16, -6, -6},
    {-17, -3, -30},
    {-13, -34, -16},
    {5, -24, -7},
    {6, -11, -10},
    {1, -20, -26},
    {-7, -8, -28}
  },
  {
    {20, 28, 21},
    {8, 7, 33},
    {45, 28, 24},
    {27, -1, 32},
    {-53, -29, 30},
    {-65, -9, 4},
    {-70, -40, 35},
    {-33, -18, 49},
    {-36, -26, 23},
    {-71, -4, 10},
    {7, 13, 7},
    {13, -2, -4},
    {1, -29, -21},
    {7, 21, -12},
    {13, -19, -2},
    {-2, -6, -6},
    {16, 32, 16},
    {17, 13, 28},
    {0, 3, -7},
    {-4, -16, -15},
    {30, -1, 4},
    {4, 10, 6},
    {-29, -39, -18},
    {-5, -1, -4},
    {11, 9, 14},
    {5, 4, 2},
    {13, 32, 5},
    {33, 29, -1},
    {18, 2, -15},
    {-7, -10, -30}
  },
  {
    {30, -4, 26},
    {11, 6, 8},
    {5, -12, 12},
    {-12, -15, -4},
    {17, 6, 11},
    {-5, -11, 5},
    {4, -5, -5},
    {-3, -6, 10},
    {4, -13, 6},
    {34, 7, 27},
    {3, 2, 28},
    {-6, 11, 1},
    {-22, 7, 1},
    {-46, 1, -17},
    {17, 16, 14},
    {5, -21, 7},
    {0, -24, -13},
    {4, -21, -3},
    {44, 14, 40},
    {53, 50, 62},
    {22, 24, 33},
    {19, -1, -5},
    {-17, 7, -5},
    {-49, -10, -42},
    {20, 10, 4},
    {-15, -17, -20},
    {-1, -5, -11},
    {-32, -5, -11},
    {29, 18, 9},
    {-9, -11, 2}
  },
  {
    {15, 16, 20},
    {7, 14, 20},
    {3, -5, -2},
    {18, -13, 4},
    {4, -10, 21},
    {17, -8, -2},
    {-13, -57, -33},
    {1, -32, -15},
    {27, -31, -3},
    {32, -31, -1},
    {18, 24, 2},
    {28, 17, 8},
    {1, 7, 31},
    {10, 7, 26},
    {3, -10, 47},
    {-13, -4, 37},
    {-45, -42, 0},
    {-24, -10, 9},
    {-13, -21, 59},
    {-7, -12, 48},
    {5, 16, 20},
    {2, 17, 14},
    {17, -13, -6},
    {9, -6, -1},
    {28, -16, -13},
    {10, -26, 15},
    {-20, -48, -33},
    {-9, -7, -18},
    {33, -9, -21},
    {25, -16, 6}
  },
  {
    {0, -2, -5},
    {8, 6, -10},
    {1, 22, 31},
    {-1, 19, 6},
    {-8, 17, 15},
    {7, -15, 5},
    {7, -10, 21},
    {-36, -10, -8},
    {10, 30, 5},
    {-28, -14, -12},
    {-1, -3, 11},
    {14, -19, 33},
    {7, 46, 49},
    {-12, 27, 25},
    {-4, -6, -16},
    {-19, -24, -5},
    {22, 45, 53},
    {-14, 13, -2},
    {12, 4, 25},
    {-9, -32, -10},
    {13, -9, -12},
    {21, 4, -9},
    {-18, 10, -9},
    {-11, 12, 4},
    {-6, -9, -11},
    {-29, -7, -5},
    {3, 26, -1},
    {-34, -12, -34},
    {-7, 3, -20},
    {-39, -25, -53}
  },
  {
    {68, 54, 29},
    {64, 32, 23},
    {1, -1, -9},
    {15, -10, -5},
    {-29, -42, -44},
    {-45, -43, -66},
    {17, 12, -3},
    {17, 5, -25},
    {19, 3, 11},
    {2, 1, 21},
    {11, 12, -9},
    {4, 11, 14},
    {-15, 4, -1},
    {1, 25, 17},
    {-10, -7, -14},
    {-17, 3, -4},
    {15, 3, 13},
    {13, 9, 10},
    {1, 1, 12},
    {17, 13, 2},
    {-20, -6, 5},
    {-2, -5, 13},
    {-17, -7, 6},
    {-1, -6, 27},
    {-4, 3, -6},
    {-1, 1, -6},
    {8, 8, 23},
    {-8, 1, 12},
    {9, 4, 5},
    {-5, 7, -5}
  },
  {
    {34, 4, 19},
    {17, 25, 9},
    {-2, 13, -11},
    {16, -1, -19},
    {10, 11, 20},
    {24, 9, 15},
    {-16, -12, -12},
    {-1, 14, 19},
    {-1, -13, -7},
    {0, -7, 6},
    {7, 9, 18},
    {10, 27, 25},
    {-11, 4, -15},
    {-11, -11, 0},
    {17, 21, 18},
    {28, 16, 25},
    {-17, -12, -18},
    {-7, -4, 18},
    {-2, -3, -3},
    {12, -10, -4},
    {9, 2, 0},
    {-13, 18, 0},
    {-15, -9, -10},
    {-17, -11, -10},
    {17, 16, 26},
    {16, 41, 30},
    {-2, -15, -9},
    {1, 6, 1},
    {-1, -15, -8},
    {-8, -20, -13}
  },
  {
    {-27, -2, -2},
    {-26, -20, -13},
    {-20, -27, 9},
    {-37, 12, -12},
    {-8, 8, 15},
    {-6, 19, 1},
    {-18, 11, 42},
    {19, 24, 11},
    {-38, -17, 22},
    {-4, -1, 17},
    {40, 62, 64},
    {9, 46, 39},
    {-25, 3, -48},
    {-35, -24, -34},
    {0, -10, -37},
    {-25, -8, -48},
    {34, -3, -5},
    {28, 35, -30},
    {-4, 19, -15},
    {9, -16, 10},
    {37, 54, 66},
    {38, 26, 22},
    {-33, -20, -18},
    {-43, -34, -18},
    {-14, 4, -24},
    {-11, -23, -24},
    {7, -5, 2},
    {33, -1, -8},
    {-4, -16, -9},
    {32, 17, 24}
  },
  {
    {-27, 4, -40},
    {-9, 3, -41},
    {-70, -34, -68},
    {-13, -22, -34},
    {48, -2, 14},
    {15, 34, 3},
    {-2, -20, -16},
    {1, 26, -4},
    {60, 77, 51},
    {49, 52, 15},
    {3, -6, 27},
    {-17, 24, 20},
    {20, 20, 23},
    {22, 27, 18},
    {-27, -15, -15},
    {-7, -24, -22},
    {-20, 2, 7},
    {10, 9, 0},
    {-16, -34, -44},
    {-14, -13, -37},
    {17, -5, 14},
    {10, 3, 27},
    {-8, -8, -3},
    {19, 12, 5},
    {-9, 13, 21},
    {-19, 3, 28},
    {-6, 7, 22},
    {2, 4, 27},
    {-46, -29, -34},
    {-35, -25, -22}
  },
  {
    {10, 0, 2},
    {21, -10, 26},
    {-21, 20, 5},
    {-30, -25, 12},
    {15, 6, 10},
    {6, 12, 8},
    {-5, -42, -5},
    {-11, 6, -19},
    {-2, -14, -8},
    {15, 7, -10},
    {23, 12, 32},
    {-10, 22, 10},
    {-11, 5, -7},
    {-35, -1, -5},
    {12, 19, 41},
    {25, 15, 22},
    {-17, -4, -12},
    {-15, -13, -22},
    {-23, -2, -31},
    {-5, -6, 1},
    {27, 31, 17},
    {7, 30, 9},
    {13, 19, -13},
    {-13, 7, 7},
    {-4, 2, -6},
    {-17, -15, -33},
    {30, 18, 76},
    {28, 18, 68},
    {-19, -40, -21},
    {-14, -6, -25}
  },
  {
    {-2, -14, -19},
    {-1, 6, -14},
    {12, 0, 6},
    {9, 15, 6},
    {-10, -1, -17},
    {0, 11, -7},
    {14, 10, 14},
    {-1, 17, 12},
    {-41, -35, -35},
    {-23, -32, -11},
    {-8, -9, -30},
    {-2, -12, -15},
    {-5, 2, -19},
    {15, 1, 6},
    {-11, 2, -8},
    {19, 4, 3},
    {-4, -5, -6},
    {2, 11, 7},
    {-19, -14, -38},
    {-19, -21, -3},
    {-22, -28, -15},
    {-10, -9, -11},
    {-1, 2, 4},
    {15, 7, 16},
    {-7, -19, 1},
    {23, 12, -2},
    {-6, 1, -8},
    {2, 13, 4},
    {1, -19, 7},
    {22, 22, 46}
  },
  {
    {-1, 1, 31},
    {30, -5, 5},
    {20, -14, -17},
    {4, -13, 1},
    {0, 16, -17},
    {10, -10, -12},
    {-9, 4, 11},
    {5, 15, -2},
    {-25, 0, -21},
    {-1, -9, 17},
    {16, 30, 24},
    {37, 38, 21},
    {32, -18, -20},
    {19, -12, 1},
    {-9, 8, 6},
    {-8, -11, -1},
    {21, 59, 48},
    {28, 46, 54},
    {-37, -15, -18},
    {-18, -18, 11},
    {3, 14, 10},
    {2, 10, 18},
    {-11, 5, 0},
    {-21, -7, -8},
    {22, 10, -24},
    {30, -10, -21},
    {-48, -37, -17},
    {-34, -17, -10},
    {5, 5, 22},
    {24, 18, 38}
  },
  {
    {-29, 10, -25},
    {-13, 15, -7},
    {-10, -15, -16},
    {-2, 28, 27},
    {11, -7, 24},
    {15, 18, 23},
    {-16, -16, -21},
    {-33, -14, -18},
    {20, 13, 3},
    {-14, -14, -27},
    {8, -5, -1},
    {24, 9, -6},
    {-21, -9, -14},
    {44, 9, 8},
    {14, 16, 4},
    {3, 13, 8},
    {6, -10, 19},
    {-1, -14, 14},
    {25, 13, 22},
    {-2, -10, -11},
    {2, -2, 16},
    {14, 25, 29},
    {-22, 7, -21},
    {20, 28, 10},
    {2, -9, 8},
    {-5, 7, 7},
    {7, -4, 14},
    {18, 17, 8},
    {31, -15, 29},
    {16, -14, 13}
  },
  {
    {9, 5, 15},
    {11, 20, 15},
    {-7, -19, -6},
    {-5, -5, 0},
    {12, 16, 10},
    {14, 8, 23},
    {7, -11, -5},
    {4, -3, 4},
    {-6, -14, -2},
    {0, -2, 2},
    {13, 21, 23},
    {17, 22, 25},
    {-11, -14, -16},
    {-14, 2, -3},
    {17, 29, 29},
    {25, 8, 27},
    {7, -4, 9},
    {1, 5, 3},
    {-2, 7, -10},
    {-3, 2, 6},
    {19, 12, 3},
    {19, 18, 10},
    {-10, -12, 0},
    {-18, -3, 2},
    {17, 18, 30},
    {2, 25, 12},
    {-4, 11, 8},
    {-6, 23, 11},
    {-13, 10, 10},
    {-26, 21, 9}
  },
  {
    {-12, -20, -4},
    {-36, -23, 2},
    {-15, -10, -1},
    {-15, -14, -27},
    {12, 9, -3},
    {-13, -25, -18},
    {-4, 19, 21},
    {11, 2, 17},
    {10, 7, 24},
    {23, 9, 36},
    {7, -20, 16},
    {-18, -11, -19},
    {10, 14, 18},
    {-2, 10, -5},
    {9, -1, 29},
    {-2, -5, -13},
    {29, 15, 13},
    {7, 26, 20},
    {-10, -13, -10},
    {1, -14, 13},
    {-26, -13, -36},
    {-22, -20, -37},
    {-25, -5, -26},
    {1, -24, -9},
    {17, 19, 24},
    {-12, -3, -5},
    {-7, 8, 4},
    {5, 1, 1},
    {-35, -14, -24},
    {-15, -6, -7}
  }
};
static const int8_t tensor__conv1_conv1_2_Relu_output_0_zero_point = 
-128;
static const float tensor__conv1_conv1_2_Relu_output_0_scale = 
0.02649778872728347778f;
static const int8_t tensor_onnx__Conv_33_zero_point = 
0;
static const float tensor_onnx__Conv_33_scale = 
0.01036576274782419205f;
static const int8_t tensor_onnx__Conv_33_quantized[32][16][3] = 
{
  {
    {40, 47, 2},
    {4, 8, 15},
    {21, 34, 42},
    {-49, -35, -37},
    {-14, -47, -17},
    {11, -21, -23},
    {-29, -13, -53},
    {-1, -9, -4},
    {-63, -3, -49},
    {37, 10, 10},
    {53, 19, 45},
    {-40, -66, -61},
    {40, 61, 56},
    {-37, 19, 5},
    {-35, -35, 3},
    {-9, -13, -14}
  },
  {
    {55, 47, 32},
    {-19, -10, -8},
    {40, -8, 20},
    {-54, -57, -62},
    {0, -10, 31},
    {-2, 9, -18},
    {-22, -17, -35},
    {-46, 6, -17},
    {-29, -3, -18},
    {-2, -30, -29},
    {33, 2, 52},
    {-40, -69, -50},
    {65, 60, 40},
    {-28, -12, -19},
    {-27, -25, 9},
    {7, 15, 3}
  },
  {
    {22, 69, 42},
    {-8, 10, 18},
    {25, 10, 37},
    {-46, -42, -57},
    {11, -21, -17},
    {14, -16, 1},
    {-35, -22, -31},
    {14, -19, 11},
    {-38, -18, -28},
    {0, -6, -10},
    {30, 33, 44},
    {-69, -55, -100},
    {34, 43, 27},
    {-17, -17, 22},
    {-36, -7, -16},
    {0, 6, -5}
  },
  {
    {9, 17, 11},
    {46, 37, 4},
    {-26, -15, -42},
    {19, -9, -8},
    {-75, -70, -73},
    {5, -35, 7},
    {27, 18, 35},
    {58, 82, 26},
    {19, 7, 10},
    {-21, 22, -26},
    {13, 31, 2},
    {-20, -17, -7},
    {3, -9, 11},
    {42, 52, 68},
    {-49, -76, -47},
    {-43, 11, -31}
  },
  {
    {56, 50, 43},
    {-33, 18, -5},
    {37, 18, 24},
    {-58, -37, -67},
    {-6, -44, 15},
    {0, 1, -11},
    {-41, -22, -55},
    {-32, -8, 9},
    {-34, -26, -22},
    {2, -3, -44},
    {34, 50, 25},
    {-29, -59, -57},
    {68, 69, 55},
    {-18, -12, -7},
    {-31, -30, -2},
    {0, 0, -8}
  },
  {
    {18, 3, 22},
    {63, 69, 36},
    {40, 46, 57},
    {-15, -15, -33},
    {4, 11, 35},
    {-24, -56, -55},
    {-80, -60, -55},
    {-56, -81, -87},
    {-76, -4, -69},
    {31, 29, 30},
    {-66, -33, -48},
    {3, -41, 3},
    {-18, -54, -13},
    {-32, -48, -39},
    {98, 58, 77},
    {-56, -58, -18}
  },
  {
    {25, 9, 14},
    {69, 78, 57},
    {66, 48, 72},
    {-30, -35, -37},
    {34, 10, 30},
    {-79, -67, -58},
    {-86, -41, -58},
    {-57, -89, -65},
    {6, -20, 12},
    {-1, 24, 2},
    {-80, -26, -59},
    {-31, -23, 3},
    {-54, -44, -39},
    {-22, -57, -33},
    {101, 87, 75},
    {-27, -23, -50}
  },
  {
    {-39, -26, -39},
    {16, 10, 41},
    {-33, -53, -56},
    {-17, -11, -27},
    {-55, -37, -37},
    {-23, -17, -1},
    {12, 28, 23},
    {10, 28, -14},
    {42, 6, 4},
    {4, -29, -17},
    {10, 41, 8},
    {-2, 8, -16},
    {6, 29, 14},
    {77, 41, 58},
    {-39, -56, 6},
    {-6, 20, 15}
  },
  {
    {8, -3, 4},
    {76, 47, 66},
    {42, 44, 50},
    {-29, -27, -30},
    {23, 8, 21},
    {-61, -54, -62},
    {-79, -38, -55},
    {-77, -65, -69},
    {-47, -19, -30},
    {30, 21, 27},
    {-66, -47, -39},
    {-3, -55, 2},
    {-38, -41, -26},
    {-26, -74, -21},
    {118, 72, 50},
    {-24, -68, -39}
  },
  {
    {22, 43, 70},
    {-18, 17, 4},
    {8, 25, 19},
    {-44, -48, -44},
    {24, -20, -29},
    {20, 0, -3},
    {-41, -24, -3},
    {6, 20, 6},
    {-39, -20, -21},
    {-15, 4, -17},
    {28, 26, 11},
    {-50, -63, -82},
    {9, 29, 47},
    {-10, -3, 22},
    {-9, 12, 14},
    {-2, 4, -5}
  },
  {
    {25, 36, 2},
    {39, 24, 12},
    {-4, -3, -37},
    {-35, 28, -5},
    {-66, -68, -68},
    {3, 4, -19},
    {-5, 41, 31},
    {56, 64, 25},
    {6, 21, 8},
    {4, -15, -7},
    {2, 1, -8},
    {-32, -11, -21},
    {3, 0, -1},
    {33, 65, 59},
    {-32, -77, -46},
    {-23, -1, -26}
  },
  {
    {22, 7, 4},
    {53, 37, 55},
    {38, 57, 47},
    {-29, -22, -35},
    {47, 15, 43},
    {-47, -83, -50},
    {-71, -48, -40},
    {-53, -89, -60},
    {-1, -19, 18},
    {-2, 12, 0},
    {-67, -46, -46},
    {-22, -67, 16},
    {-52, -45, -46},
    {-24, -63, -30},
    {79, 123, 42},
    {-19, -21, -44}
  },
  {
    {25, 6, 13},
    {71, 10, 42},
    {32, 50, 33},
    {-12, -7, -16},
    {-4, 20, 11},
    {-34, -36, 0},
    {-71, -67, -50},
    {-44, -84, -57},
    {-71, -32, -63},
    {33, 16, 41},
    {-39, -28, -27},
    {-17, -23, 12},
    {-10, -18, -12},
    {-12, -52, -26},
    {43, 74, 39},
    {-35, -28, -47}
  },
  {
    {-12, -1, 8},
    {-59, -54, -66},
    {-69, -37, -32},
    {4, -45, -33},
    {16, 18, 33},
    {-4, 47, -6},
    {35, 22, 36},
    {41, 10, 43},
    {45, -16, 24},
    {-54, -38, -61},
    {25, -8, -5},
    {-47, -28, -59},
    {29, 14, 1},
    {-3, 33, -7},
    {14, -55, 42},
    {49, 39, 70}
  },
  {
    {0, 12, -13},
    {-60, -42, -45},
    {-66, -45, -61},
    {-37, -1, -20},
    {0, 13, 15},
    {-16, 37, -20},
    {26, 31, 14},
    {43, 42, -1},
    {10, -45, 20},
    {-51, -19, -52},
    {56, 10, 44},
    {-40, -29, -26},
    {45, 70, 19},
    {8, 44, 19},
    {0, 7, -7},
    {34, 68, 42}
  },
  {
    {-25, -3, -31},
    {19, -44, 12},
    {-47, -25, -52},
    {24, -24, 3},
    {-66, -44, -65},
    {-9, 22, 11},
    {66, 7, 40},
    {84, 54, 107},
    {-2, -9, 2},
    {5, -8, 17},
    {-18, 33, -32},
    {10, -27, 19},
    {8, 42, 3},
    {20, 19, -18},
    {-90, -66, -69},
    {-1, 10, 12}
  },
  {
    {36, 62, 48},
    {-16, 8, 5},
    {29, 14, 30},
    {-50, -38, -57},
    {-1, -13, -10},
    {5, 1, -5},
    {-39, -20, -42},
    {-2, -4, -7},
    {-29, -22, -18},
    {-8, -8, -36},
    {36, 23, 35},
    {-37, -72, -66},
    {44, 36, 61},
    {-19, -16, 14},
    {-21, -12, -21},
    {-5, 9, -7}
  },
  {
    {-18, -2, -16},
    {-25, -22, -38},
    {-9, -24, -18},
    {-38, -53, -48},
    {77, 29, 53},
    {-31, 11, -30},
    {28, 14, 37},
    {-14, -34, 19},
    {50, 24, 51},
    {-45, -23, -49},
    {-33, -30, -40},
    {-41, -53, -36},
    {-50, -1, -64},
    {-20, -27, -19},
    {71, 43, 58},
    {32, 12, 43}
  },
  {
    {-26, -3, -30},
    {16, 20, 15},
    {31, 1, 27},
    {-38, -24, -40},
    {61, 4, 47},
    {-54, -30, -71},
    {7, -3, 13},
    {-33, -5, -35},
    {25, 24, 49},
    {-18, -2, -20},
    {-45, -32, -47},
    {-26, -48, -21},
    {-57, -21, -58},
    {-44, -36, -28},
    {59, 13, 48},
    {-17, -4, -19}
  },
  {
    {-2, -19, 19},
    {-52, -44, -79},
    {-52, -67, -64},
    {-11, -26, -37},
    {0, -5, 48},
    {14, -3, 24},
    {21, 57, 41},
    {34, 29, 39},
    {45, 2, -1},
    {-63, -28, -69},
    {36, -13, 43},
    {-56, -2, -64},
    {22, 9, 45},
    {38, -2, 25},
    {-29, 13, -24},
    {36, 51, 72}
  },
  {
    {-20, -32, -13},
    {-7, 0, 11},
    {-57, -26, -48},
    {9, 26, -1},
    {-66, -65, -44},
    {2, 1, 11},
    {57, 52, 3},
    {63, 97, 71},
    {-11, 6, -20},
    {-2, 16, 13},
    {6, 27, -17},
    {2, 43, -5},
    {15, 29, 16},
    {47, -10, 21},
    {-92, -72, -80},
    {-21, 21, 8}
  },
  {
    {28, 5, 13},
    {66, 67, 51},
    {42, 42, 62},
    {-33, -12, -26},
    {8, 12, 32},
    {-69, -39, -43},
    {-71, -70, -53},
    {-56, -77, -86},
    {-68, -27, -51},
    {22, 21, 40},
    {-37, -52, -45},
    {-23, -47, 25},
    {-8, -45, -33},
    {-9, -73, -32},
    {59, 96, 70},
    {-20, -61, -42}
  },
  {
    {2, 35, 43},
    {-57, -11, 8},
    {-8, 22, 58},
    {-32, -45, -70},
    {26, -52, -19},
    {34, -18, -35},
    {-34, -8, -32},
    {-10, 3, -19},
    {-42, -30, -40},
    {16, 23, 15},
    {40, 30, 66},
    {-25, -59, -101},
    {48, 86, 77},
    {-70, 35, 14},
    {-8, -36, -29},
    {1, 2, 19}
  },
  {
    {53, 18, 24},
    {55, 14, 60},
    {37, 54, 45},
    {-4, -4, -6},
    {-30, -38, -7},
    {-66, -33, -42},
    {-70, -49, -64},
    {-55, -28, -54},
    {-63, -32, -83},
    {55, 16, 47},
    {-7, 8, 19},
    {-16, -21, 12},
    {42, 34, 31},
    {-11, 6, -18},
    {5, -32, -5},
    {-41, -6, -45}
  },
  {
    {42, 66, 39},
    {-26, 11, -4},
    {5, 35, 35},
    {-45, -48, -60},
    {1, -40, -4},
    {18, -1, -22},
    {-8, -53, -44},
    {-8, 11, -19},
    {-30, -20, -37},
    {5, -6, -28},
    {5, 64, 51},
    {-23, -73, -66},
    {45, 66, 89},
    {-16, -29, 17},
    {-38, -17, -17},
    {-21, 14, -4}
  },
  {
    {55, 48, 38},
    {-18, 0, 1},
    {57, 14, -5},
    {-50, -39, -29},
    {-17, -40, 32},
    {-11, 10, -3},
    {-48, 1, -58},
    {-22, 5, 18},
    {-21, -31, -15},
    {1, -16, -48},
    {27, 9, 39},
    {-53, -37, -53},
    {58, 63, 11},
    {-4, -5, -4},
    {1, -23, -8},
    {-16, 14, -18}
  },
  {
    {-51, -9, -56},
    {-13, 9, 13},
    {-38, -66, -65},
    {3, -11, -18},
    {-85, -44, -52},
    {-8, 1, 3},
    {46, 17, 53},
    {48, 26, 54},
    {6, 16, 9},
    {2, -14, -4},
    {23, 36, 2},
    {-29, 38, -16},
    {34, 28, 33},
    {29, 71, 20},
    {-11, -42, -68},
    {19, 22, -7}
  },
  {
    {23, 10, 13},
    {43, 71, 36},
    {52, 35, 66},
    {-3, -52, -4},
    {18, 22, 21},
    {-47, -26, -37},
    {-95, -45, -60},
    {-64, -91, -61},
    {-75, -12, -55},
    {18, 31, 29},
    {-52, -44, -38},
    {-31, -9, -4},
    {-8, -57, -19},
    {-8, -85, -25},
    {72, 127, 36},
    {-28, -57, -44}
  },
  {
    {26, 26, 7},
    {43, 22, 36},
    {18, 35, 51},
    {0, 3, 13},
    {-41, -45, -22},
    {-34, -48, -43},
    {-44, -21, -63},
    {-12, -10, -41},
    {-46, -36, -69},
    {45, 16, 49},
    {4, 38, -2},
    {-7, -15, 6},
    {39, 48, 24},
    {7, 10, 1},
    {-34, -60, -4},
    {-45, 9, -41}
  },
  {
    {10, 17, 13},
    {83, 29, -10},
    {-1, 0, 20},
    {29, 40, 22},
    {-57, -58, -74},
    {-57, -4, -28},
    {5, 1, -12},
    {22, 34, 17},
    {-14, 9, -20},
    {25, 25, 22},
    {43, 10, 7},
    {-2, 2, -7},
    {17, 23, -23},
    {57, 15, 40},
    {-59, -53, -29},
    {-56, 8, -53}
  },
  {
    {23, 22, 9},
    {37, 53, 41},
    {6, 38, 38},
    {6, 13, 27},
    {-49, -51, -47},
    {-47, -24, -53},
    {-19, -32, -38},
    {-7, -5, 4},
    {-44, -16, -82},
    {41, 40, 43},
    {35, -10, 35},
    {-8, 10, 5},
    {16, 66, -1},
    {44, -2, 39},
    {-39, -39, -86},
    {-38, -19, -40}
  },
  {
    {-16, -23, -22},
    {78, 56, 94},
    {-26, 18, -1},
    {-1, -95, -68},
    {-16, -59, -13},
    {-57, -53, -73},
    {44, 16, 20},
    {36, 16, 12},
    {68, 30, 82},
    {-12, -22, -32},
    {-79, -3, -91},
    {1, -50, -8},
    {-77, -66, -59},
    {-39, -67, -42},
    {41, 59, 75},
    {-28, -21, 11}
  }
};
static const int8_t tensor__conv2_conv2_2_Relu_output_0_zero_point = 
-128;
static const float tensor__conv2_conv2_2_Relu_output_0_scale = 
0.03537274524569511414f;
static const int8_t tensor__conv2_conv2_3_GlobalAveragePool_output_0_zero_point = 
-128;
static const float tensor__conv2_conv2_3_GlobalAveragePool_output_0_scale = 
0.01258028205484151840f;
static const int8_t tensor_sleep_stage_logits_zero_point = 
50;
static const float tensor_sleep_stage_logits_scale = 
0.08031430095434188843f;
static const int8_t tensor_fc_weight_zero_point = 
0;
static const float tensor_fc_weight_scale = 
0.00887928996235132217f;
static const int8_t tensor_fc_weight_quantized[4][32] = 
{
  {-65, -127, -64, 42, -84, -38, -46, 26, -37, -13, 42, -59, -58, 27, 21, 25, -71, 22, -2, 26, 24, -30, -84, -77, -81, -61, 25, -49, -61, 26, -6, 28},
  {29, 10, 18, 21, 26, 20, 16, 14, 18, 14, 21, 13, 26, -36, -11, 21, 28, -46, -44, -28, 23, 36, 7, 21, 12, 15, 13, 30, 42, 16, 35, 11},
  {34, 21, 28, -32, 31, -61, -76, -79, -69, 22, -34, -60, -57, 25, 11, -78, 36, 14, -14, 22, -69, -49, 17, -31, 19, 23, -56, -48, -21, -34, -30, -76},
  {-50, -37, -73, -38, -50, 33, 41, -10, 34, -106, -42, 49, 36, -46, -78, -4, -57, 32, 61, -66, -5, 49, -67, 4, -62, -93, -28, 45, -8, -44, -19, 29}
};
static const int32_t tensor_onnx__Conv_31_quantized[16] = 
{112, 39, 4086, 3162, 3069, -2180, -2170, 4207, -1196, -12, 1463, 4223, 403, 4110, -139, 1644};
static const float tensor_onnx__Conv_31_quantized_scale[1] = 
{0.00013939492055214942f};
static const int32_t tensor_onnx__Conv_31_quantized_zero_point = 
0;
static const int32_t tensor_onnx__Conv_34_quantized[32] = 
{3800, 5470, 4819, -319, 4432, 9572, 7535, 2417, 10735, 3550, -212, 8359, 7318, 2112, 383, 2283, 4463, 7149, 7305, 1507, 184, 9188, 4072, 2713, 4130, 3231, 1852, 8564, 406, -2502, -1657, 12237};
static const float tensor_onnx__Conv_34_quantized_scale[1] = 
{0.00027466978644952178f};
static const int32_t tensor_onnx__Conv_34_quantized_zero_point = 
0;
static const int32_t tensor_fc_bias_quantized[4] = 
{4881, -4878, -1296, 1472};
static const float tensor_fc_bias_quantized_scale[1] = 
{0.00011170397192472592f};
static const int32_t tensor_fc_bias_quantized_zero_point = 
0;
static const int64_t tensor__Constant_output_0[1] = 
{2};
union tensor_union_0 {
float tensor_fc_bias[4];
int8_t tensor_sleep_stage_logits_QuantizeLinear_Output[1][4];
};
static union tensor_union_0 tu0;

union tensor_union_1 {
float tensor_fc_weight_DequantizeLinear_Output[4][32];
};
static union tensor_union_1 tu1;

union tensor_union_2 {
float tensor__Transpose_output_0[1][30][120];
float tensor__Transpose_output_0_DequantizeLinear_Output[1][30][120];
int8_t tensor__conv1_conv1_2_Relu_output_0_QuantizeLinear_Output[1][16][120];
float tensor__conv1_conv1_3_MaxPool_output_0[1][16][60];
float tensor__conv1_conv1_3_MaxPool_output_0_DequantizeLinear_Output[1][16][60];
int8_t tensor__conv2_conv2_2_Relu_output_0_QuantizeLinear_Output[1][32][60];
float tensor__conv2_conv2_3_GlobalAveragePool_output_0[1][32][1];
float tensor__conv2_conv2_3_GlobalAveragePool_output_0_DequantizeLinear_Output[1][32][1];
int8_t tensor__Squeeze_output_0_QuantizeLinear_Output[1][32];
float tensor_sleep_stage_logits_QuantizeLinear_Input[1][4];
};
static union tensor_union_2 tu2;

union tensor_union_3 {
float tensor_onnx__Conv_30_DequantizeLinear_Output[16][30][3];
float tensor__conv1_conv1_2_Relu_output_0_DequantizeLinear_Output[1][16][120];
int8_t tensor__conv1_conv1_3_MaxPool_output_0_QuantizeLinear_Output[1][16][60];
float tensor__conv2_conv2_2_Relu_output_0[1][32][60];
float tensor__conv2_conv2_2_Relu_output_0_DequantizeLinear_Output[1][32][60];
int8_t tensor__conv2_conv2_3_GlobalAveragePool_output_0_QuantizeLinear_Output[1][32][1];
float tensor__Squeeze_output_0[1][32];
float tensor__Squeeze_output_0_DequantizeLinear_Output[1][32];
};
static union tensor_union_3 tu3;

union tensor_union_4 {
float tensor_onnx__Conv_31[16];
};
static union tensor_union_4 tu4;

union tensor_union_5 {
float tensor_onnx__Conv_33_DequantizeLinear_Output[32][16][3];
};
static union tensor_union_5 tu5;

union tensor_union_6 {
float tensor_onnx__Conv_34[32];
};
static union tensor_union_6 tu6;

union tensor_union_7 {
int8_t tensor__Transpose_output_0_QuantizeLinear_Output[1][30][120];
float tensor__conv1_conv1_2_Relu_output_0[1][16][120];
};
static union tensor_union_7 tu7;


/*
 * Operand:           Constant
 * Name in ONNX file: /Constant
 */
FUNC_PREFIX void node__Constant( const int64_t output[1] )
{
	/* Constant */
	/* The output is generated as a global tensor */
	(void)output;
}

/*
 * Operand:           DequantizeLinear
 * Name in ONNX file: fc.bias_DequantizeLinear
 */
FUNC_PREFIX void node_fc_bias_DequantizeLinear( const int32_t x[4], const float x_scale[1], const int32_t *x_zero_point, float y[4] )
{
	/* DequantizeLinear */
	for (unsigned i0 = 0; i0 < 4; i0++)
	{
		y[i0] = (x[i0] - x_zero_point[0]) * x_scale[0];
	}
}

/*
 * Operand:           DequantizeLinear
 * Name in ONNX file: fc.weight_DequantizeLinear
 */
FUNC_PREFIX void node_fc_weight_DequantizeLinear( const int8_t x[4][32], const float *x_scale, const int8_t *x_zero_point, float y[4][32] )
{
	/* DequantizeLinear */
	for (unsigned i0 = 0; i0 < 4; i0++)
	for (unsigned i1 = 0; i1 < 32; i1++)
	{
		y[i0][i1] = (x[i0][i1] - x_zero_point[0]) * x_scale[0];
	}
}

/*
 * Operand:           Transpose
 * Name in ONNX file: /Transpose
 */
FUNC_PREFIX void node__Transpose( const float input[1][120][30], float output[1][30][120] )
{
	/* Transpose
	 * perm = 0 2 1 
	 */
	for( uint32_t i0=0; i0<1; i0++ ) {
	for( uint32_t i1=0; i1<120; i1++ ) {
	for( uint32_t i2=0; i2<30; i2++ ) {
		output[i0][i2][i1] = input[i0][i1][i2];
	}
	}
	}
}

/*
 * Operand:           DequantizeLinear
 * Name in ONNX file: onnx::Conv_30_DequantizeLinear
 */
FUNC_PREFIX void node_onnx__Conv_30_DequantizeLinear( const int8_t x[16][30][3], const float *x_scale, const int8_t *x_zero_point, float y[16][30][3] )
{
	/* DequantizeLinear */
	for (unsigned i0 = 0; i0 < 16; i0++)
	for (unsigned i1 = 0; i1 < 30; i1++)
	for (unsigned i2 = 0; i2 < 3; i2++)
	{
		y[i0][i1][i2] = (x[i0][i1][i2] - x_zero_point[0]) * x_scale[0];
	}
}

/*
 * Operand:           DequantizeLinear
 * Name in ONNX file: onnx::Conv_31_DequantizeLinear
 */
FUNC_PREFIX void node_onnx__Conv_31_DequantizeLinear( const int32_t x[16], const float x_scale[1], const int32_t *x_zero_point, float y[16] )
{
	/* DequantizeLinear */
	for (unsigned i0 = 0; i0 < 16; i0++)
	{
		y[i0] = (x[i0] - x_zero_point[0]) * x_scale[0];
	}
}

/*
 * Operand:           DequantizeLinear
 * Name in ONNX file: onnx::Conv_33_DequantizeLinear
 */
FUNC_PREFIX void node_onnx__Conv_33_DequantizeLinear( const int8_t x[32][16][3], const float *x_scale, const int8_t *x_zero_point, float y[32][16][3] )
{
	/* DequantizeLinear */
	for (unsigned i0 = 0; i0 < 32; i0++)
	for (unsigned i1 = 0; i1 < 16; i1++)
	for (unsigned i2 = 0; i2 < 3; i2++)
	{
		y[i0][i1][i2] = (x[i0][i1][i2] - x_zero_point[0]) * x_scale[0];
	}
}

/*
 * Operand:           DequantizeLinear
 * Name in ONNX file: onnx::Conv_34_DequantizeLinear
 */
FUNC_PREFIX void node_onnx__Conv_34_DequantizeLinear( const int32_t x[32], const float x_scale[1], const int32_t *x_zero_point, float y[32] )
{
	/* DequantizeLinear */
	for (unsigned i0 = 0; i0 < 32; i0++)
	{
		y[i0] = (x[i0] - x_zero_point[0]) * x_scale[0];
	}
}

/*
 * Operand:           QuantizeLinear
 * Name in ONNX file: /Transpose_output_0_QuantizeLinear
 */
FUNC_PREFIX void node__Transpose_output_0_QuantizeLinear( const float x[1][30][120], const float *y_scale, const int8_t *y_zero_point, int8_t y[1][30][120] )
{
	/* QuantizeLinear */
	for (unsigned i0 = 0; i0 < 1; i0++)
	for (unsigned i1 = 0; i1 < 30; i1++)
	for (unsigned i2 = 0; i2 < 120; i2++)
	{
		int t = (int)roundf(x[i0][i1][i2] / y_scale[0]) + (int)y_zero_point[0];
		y[i0][i1][i2] = (int8_t)MIN(MAX(t, INT8_MIN), INT8_MAX);
	}
}

/*
 * Operand:           DequantizeLinear
 * Name in ONNX file: /Transpose_output_0_DequantizeLinear
 */
FUNC_PREFIX void node__Transpose_output_0_DequantizeLinear( const int8_t x[1][30][120], const float *x_scale, const int8_t *x_zero_point, float y[1][30][120] )
{
	/* DequantizeLinear */
	for (unsigned i0 = 0; i0 < 1; i0++)
	for (unsigned i1 = 0; i1 < 30; i1++)
	for (unsigned i2 = 0; i2 < 120; i2++)
	{
		y[i0][i1][i2] = (x[i0][i1][i2] - x_zero_point[0]) * x_scale[0];
	}
}

/*
 * Operand:           Conv
 * Name in ONNX file: /conv1/conv1.0/Conv
 */
FUNC_PREFIX void node__conv1_conv1_0_Conv( const float x[1][30][120], const float w[16][30][3], const float bias[16], float y[1][16][120] )
{
	/* Conv
	 *
	 * auto_pad: NOTSET
	 * dilations: 1 
	 * group: 1
	 * kernel_shape: 3 
	 * pads: 1 1 
	 * strides: 1 
	 */
	for( uint32_t b=0; b<1; b++ ) {
	for( uint32_t m=0; m<16; m++) {
		for( int32_t o0=0, i0=-1; o0<120; o0++, i0+=1) {
			y[b][m][o0] = bias[m];
			for( int32_t c=0; c<30; c++ ) {
			for( uint32_t k0=0; k0<3; k0++ ) {
				int ii0 = i0+k0 * 1;
				if( ii0 >= 0 && ii0 < 120 ) {
				y[b][m][o0] += x[b][c][ii0] * w[m][c][k0];
				} /* if valid */
			} /* k */
			} /* c */
		} /* o */
	} /* m */
	} /* b */
}

/*
 * Operand:           QuantizeLinear
 * Name in ONNX file: /conv1/conv1.2/Relu_output_0_QuantizeLinear
 */
FUNC_PREFIX void node__conv1_conv1_2_Relu_output_0_QuantizeLinear( const float x[1][16][120], const float *y_scale, const int8_t *y_zero_point, int8_t y[1][16][120] )
{
	/* QuantizeLinear */
	for (unsigned i0 = 0; i0 < 1; i0++)
	for (unsigned i1 = 0; i1 < 16; i1++)
	for (unsigned i2 = 0; i2 < 120; i2++)
	{
		int t = (int)roundf(x[i0][i1][i2] / y_scale[0]) + (int)y_zero_point[0];
		y[i0][i1][i2] = (int8_t)MIN(MAX(t, INT8_MIN), INT8_MAX);
	}
}

/*
 * Operand:           DequantizeLinear
 * Name in ONNX file: /conv1/conv1.2/Relu_output_0_DequantizeLinear
 */
FUNC_PREFIX void node__conv1_conv1_2_Relu_output_0_DequantizeLinear( const int8_t x[1][16][120], const float *x_scale, const int8_t *x_zero_point, float y[1][16][120] )
{
	/* DequantizeLinear */
	for (unsigned i0 = 0; i0 < 1; i0++)
	for (unsigned i1 = 0; i1 < 16; i1++)
	for (unsigned i2 = 0; i2 < 120; i2++)
	{
		y[i0][i1][i2] = (x[i0][i1][i2] - x_zero_point[0]) * x_scale[0];
	}
}

/*
 * Operand:           MaxPool
 * Name in ONNX file: /conv1/conv1.3/MaxPool
 */
FUNC_PREFIX void node__conv1_conv1_3_MaxPool( const float x[1][16][120], float y[1][16][60] )
{
	/* MaxPool
	 *
	 * auto_pad: NOTSET
	 * dilations: 1 
	 * group: 1
	 * kernel_shape: 2 
	 * pads: 0 0 
	 * strides: 2 
	 */
	for( uint32_t b=0; b<1; b++ ) {
	for( uint32_t m=0, c=0; m<16; m++, c=m) {
		for( int32_t o0=0, i0=0; o0<60; o0++, i0+=2) {
			float curmax = (float) -INFINITY;
			for( uint32_t k0=0; k0<2; k0++ ) {
				int ii0 = i0+k0 * 1;
				if( curmax < x[b][c][ii0]) {
				curmax = x[b][c][ii0];
				}
			} /* k */
			y[b][m][o0]= curmax;
		} /* o */
	} /* m */
	} /* b */
}

/*
 * Operand:           QuantizeLinear
 * Name in ONNX file: /conv1/conv1.3/MaxPool_output_0_QuantizeLinear
 */
FUNC_PREFIX void node__conv1_conv1_3_MaxPool_output_0_QuantizeLinear( const float x[1][16][60], const float *y_scale, const int8_t *y_zero_point, int8_t y[1][16][60] )
{
	/* QuantizeLinear */
	for (unsigned i0 = 0; i0 < 1; i0++)
	for (unsigned i1 = 0; i1 < 16; i1++)
	for (unsigned i2 = 0; i2 < 60; i2++)
	{
		int t = (int)roundf(x[i0][i1][i2] / y_scale[0]) + (int)y_zero_point[0];
		y[i0][i1][i2] = (int8_t)MIN(MAX(t, INT8_MIN), INT8_MAX);
	}
}

/*
 * Operand:           DequantizeLinear
 * Name in ONNX file: /conv1/conv1.3/MaxPool_output_0_DequantizeLinear
 */
FUNC_PREFIX void node__conv1_conv1_3_MaxPool_output_0_DequantizeLinear( const int8_t x[1][16][60], const float *x_scale, const int8_t *x_zero_point, float y[1][16][60] )
{
	/* DequantizeLinear */
	for (unsigned i0 = 0; i0 < 1; i0++)
	for (unsigned i1 = 0; i1 < 16; i1++)
	for (unsigned i2 = 0; i2 < 60; i2++)
	{
		y[i0][i1][i2] = (x[i0][i1][i2] - x_zero_point[0]) * x_scale[0];
	}
}

/*
 * Operand:           Conv
 * Name in ONNX file: /conv2/conv2.0/Conv
 */
FUNC_PREFIX void node__conv2_conv2_0_Conv( const float x[1][16][60], const float w[32][16][3], const float bias[32], float y[1][32][60] )
{
	/* Conv
	 *
	 * auto_pad: NOTSET
	 * dilations: 1 
	 * group: 1
	 * kernel_shape: 3 
	 * pads: 1 1 
	 * strides: 1 
	 */
	for( uint32_t b=0; b<1; b++ ) {
	for( uint32_t m=0; m<32; m++) {
		for( int32_t o0=0, i0=-1; o0<60; o0++, i0+=1) {
			y[b][m][o0] = bias[m];
			for( int32_t c=0; c<16; c++ ) {
			for( uint32_t k0=0; k0<3; k0++ ) {
				int ii0 = i0+k0 * 1;
				if( ii0 >= 0 && ii0 < 60 ) {
				y[b][m][o0] += x[b][c][ii0] * w[m][c][k0];
				} /* if valid */
			} /* k */
			} /* c */
		} /* o */
	} /* m */
	} /* b */
}

/*
 * Operand:           QuantizeLinear
 * Name in ONNX file: /conv2/conv2.2/Relu_output_0_QuantizeLinear
 */
FUNC_PREFIX void node__conv2_conv2_2_Relu_output_0_QuantizeLinear( const float x[1][32][60], const float *y_scale, const int8_t *y_zero_point, int8_t y[1][32][60] )
{
	/* QuantizeLinear */
	for (unsigned i0 = 0; i0 < 1; i0++)
	for (unsigned i1 = 0; i1 < 32; i1++)
	for (unsigned i2 = 0; i2 < 60; i2++)
	{
		int t = (int)roundf(x[i0][i1][i2] / y_scale[0]) + (int)y_zero_point[0];
		y[i0][i1][i2] = (int8_t)MIN(MAX(t, INT8_MIN), INT8_MAX);
	}
}

/*
 * Operand:           DequantizeLinear
 * Name in ONNX file: /conv2/conv2.2/Relu_output_0_DequantizeLinear
 */
FUNC_PREFIX void node__conv2_conv2_2_Relu_output_0_DequantizeLinear( const int8_t x[1][32][60], const float *x_scale, const int8_t *x_zero_point, float y[1][32][60] )
{
	/* DequantizeLinear */
	for (unsigned i0 = 0; i0 < 1; i0++)
	for (unsigned i1 = 0; i1 < 32; i1++)
	for (unsigned i2 = 0; i2 < 60; i2++)
	{
		y[i0][i1][i2] = (x[i0][i1][i2] - x_zero_point[0]) * x_scale[0];
	}
}

/*
 * Operand:           GlobalAveragePool
 * Name in ONNX file: /conv2/conv2.3/GlobalAveragePool
 */
FUNC_PREFIX void node__conv2_conv2_3_GlobalAveragePool( const float input[1][32][60], float output[1][32][1] )
{
	/* GlobalAveragePool */
	for( int32_t b=0; b<1; b++ ) {
	for( int32_t c=0; c<32; c++ ) {
		float dimsum=0.0f;
		for( int32_t d0 = 0; d0<60; d0++ ) {
			dimsum +=  input[b][c][d0];
		}
		output[b][c][0] = dimsum / 60;
	}
	}
}

/*
 * Operand:           QuantizeLinear
 * Name in ONNX file: /conv2/conv2.3/GlobalAveragePool_output_0_QuantizeLinear
 */
FUNC_PREFIX void node__conv2_conv2_3_GlobalAveragePool_output_0_QuantizeLinear( const float x[1][32][1], const float *y_scale, const int8_t *y_zero_point, int8_t y[1][32][1] )
{
	/* QuantizeLinear */
	for (unsigned i0 = 0; i0 < 1; i0++)
	for (unsigned i1 = 0; i1 < 32; i1++)
	for (unsigned i2 = 0; i2 < 1; i2++)
	{
		int t = (int)roundf(x[i0][i1][i2] / y_scale[0]) + (int)y_zero_point[0];
		y[i0][i1][i2] = (int8_t)MIN(MAX(t, INT8_MIN), INT8_MAX);
	}
}

/*
 * Operand:           DequantizeLinear
 * Name in ONNX file: /conv2/conv2.3/GlobalAveragePool_output_0_DequantizeLinear
 */
FUNC_PREFIX void node__conv2_conv2_3_GlobalAveragePool_output_0_DequantizeLinear( const int8_t x[1][32][1], const float *x_scale, const int8_t *x_zero_point, float y[1][32][1] )
{
	/* DequantizeLinear */
	for (unsigned i0 = 0; i0 < 1; i0++)
	for (unsigned i1 = 0; i1 < 32; i1++)
	for (unsigned i2 = 0; i2 < 1; i2++)
	{
		y[i0][i1][i2] = (x[i0][i1][i2] - x_zero_point[0]) * x_scale[0];
	}
}

/*
 * Operand:           Squeeze
 * Name in ONNX file: /Squeeze
 */
FUNC_PREFIX void node__Squeeze( const float input[1][32][1], const int64_t axes_tensor[1], float output[1][32] )
{
	/*Squeeze*/
	float *data = (float*)input;
	float *squeezed= (float*)output;
	for( uint32_t i=0; i<32; i++ )
		squeezed[i] = data[i];

}

/*
 * Operand:           QuantizeLinear
 * Name in ONNX file: /Squeeze_output_0_QuantizeLinear
 */
FUNC_PREFIX void node__Squeeze_output_0_QuantizeLinear( const float x[1][32], const float *y_scale, const int8_t *y_zero_point, int8_t y[1][32] )
{
	/* QuantizeLinear */
	for (unsigned i0 = 0; i0 < 1; i0++)
	for (unsigned i1 = 0; i1 < 32; i1++)
	{
		int t = (int)roundf(x[i0][i1] / y_scale[0]) + (int)y_zero_point[0];
		y[i0][i1] = (int8_t)MIN(MAX(t, INT8_MIN), INT8_MAX);
	}
}

/*
 * Operand:           DequantizeLinear
 * Name in ONNX file: /Squeeze_output_0_DequantizeLinear
 */
FUNC_PREFIX void node__Squeeze_output_0_DequantizeLinear( const int8_t x[1][32], const float *x_scale, const int8_t *x_zero_point, float y[1][32] )
{
	/* DequantizeLinear */
	for (unsigned i0 = 0; i0 < 1; i0++)
	for (unsigned i1 = 0; i1 < 32; i1++)
	{
		y[i0][i1] = (x[i0][i1] - x_zero_point[0]) * x_scale[0];
	}
}

/*
 * Operand:           Gemm
 * Name in ONNX file: /fc/Gemm
 */
FUNC_PREFIX void node__fc_Gemm( const float A[1][32], const float B[4][32], const float C[4], float Y[1][4] )
{
	/* Gemm */
	/* alpha   = 1.00000000000000000000
	   beta    = 1.00000000000000000000
	   transA  = 0
	   transB  = 1
	 */
	const int M = 1;
	const int K = 32;
	const int N = 4;
	float alpha = 1.00000000000000000000;
	float beta = 1.00000000000000000000;
	float (*C_)[4]  = (float(*)[4])C;
	for( uint32_t r=0; r<M; r++ )
		for( uint32_t c=0; c<N; c++ ) {
			float ABrc = 0;
			for( uint32_t i=0; i<K; i++ ) {
				float B_el = B[c][i];
				ABrc += A[r][i] * B_el;
			}
			float tmp = ABrc * alpha;
			tmp += C_[0][c] * beta;
			Y[r][c] = tmp;
	}
}

/*
 * Operand:           QuantizeLinear
 * Name in ONNX file: sleep_stage_logits_QuantizeLinear
 */
FUNC_PREFIX void node_sleep_stage_logits_QuantizeLinear( const float x[1][4], const float *y_scale, const int8_t *y_zero_point, int8_t y[1][4] )
{
	/* QuantizeLinear */
	for (unsigned i0 = 0; i0 < 1; i0++)
	for (unsigned i1 = 0; i1 < 4; i1++)
	{
		int t = (int)roundf(x[i0][i1] / y_scale[0]) + (int)y_zero_point[0];
		y[i0][i1] = (int8_t)MIN(MAX(t, INT8_MIN), INT8_MAX);
	}
}

/*
 * Operand:           DequantizeLinear
 * Name in ONNX file: sleep_stage_logits_DequantizeLinear
 */
FUNC_PREFIX void node_sleep_stage_logits_DequantizeLinear( const int8_t x[1][4], const float *x_scale, const int8_t *x_zero_point, float y[1][4] )
{
	/* DequantizeLinear */
	for (unsigned i0 = 0; i0 < 1; i0++)
	for (unsigned i1 = 0; i1 < 4; i1++)
	{
		y[i0][i1] = (x[i0][i1] - x_zero_point[0]) * x_scale[0];
	}
}


void entry(const float tensor_input_features[1][120][30], float tensor_sleep_stage_logits[1][4]){
	node__Constant( tensor__Constant_output_0);
	node_fc_bias_DequantizeLinear( tensor_fc_bias_quantized, tensor_fc_bias_quantized_scale, &tensor_fc_bias_quantized_zero_point, tu0.tensor_fc_bias);
	node_fc_weight_DequantizeLinear( tensor_fc_weight_quantized, &tensor_fc_weight_scale, &tensor_fc_weight_zero_point, tu1.tensor_fc_weight_DequantizeLinear_Output);
	node__Transpose( tensor_input_features, tu2.tensor__Transpose_output_0);
	node_onnx__Conv_30_DequantizeLinear( tensor_onnx__Conv_30_quantized, &tensor_onnx__Conv_30_scale, &tensor_onnx__Conv_30_zero_point, tu3.tensor_onnx__Conv_30_DequantizeLinear_Output);
	node_onnx__Conv_31_DequantizeLinear( tensor_onnx__Conv_31_quantized, tensor_onnx__Conv_31_quantized_scale, &tensor_onnx__Conv_31_quantized_zero_point, tu4.tensor_onnx__Conv_31);
	node_onnx__Conv_33_DequantizeLinear( tensor_onnx__Conv_33_quantized, &tensor_onnx__Conv_33_scale, &tensor_onnx__Conv_33_zero_point, tu5.tensor_onnx__Conv_33_DequantizeLinear_Output);
	node_onnx__Conv_34_DequantizeLinear( tensor_onnx__Conv_34_quantized, tensor_onnx__Conv_34_quantized_scale, &tensor_onnx__Conv_34_quantized_zero_point, tu6.tensor_onnx__Conv_34);
	node__Transpose_output_0_QuantizeLinear( tu2.tensor__Transpose_output_0, &tensor__Transpose_output_0_scale, &tensor__Transpose_output_0_zero_point, tu7.tensor__Transpose_output_0_QuantizeLinear_Output);
	node__Transpose_output_0_DequantizeLinear( tu7.tensor__Transpose_output_0_QuantizeLinear_Output, &tensor__Transpose_output_0_scale, &tensor__Transpose_output_0_zero_point, tu2.tensor__Transpose_output_0_DequantizeLinear_Output);
	node__conv1_conv1_0_Conv( tu2.tensor__Transpose_output_0_DequantizeLinear_Output, tu3.tensor_onnx__Conv_30_DequantizeLinear_Output, tu4.tensor_onnx__Conv_31, tu7.tensor__conv1_conv1_2_Relu_output_0);
	node__conv1_conv1_2_Relu_output_0_QuantizeLinear( tu7.tensor__conv1_conv1_2_Relu_output_0, &tensor__conv1_conv1_2_Relu_output_0_scale, &tensor__conv1_conv1_2_Relu_output_0_zero_point, tu2.tensor__conv1_conv1_2_Relu_output_0_QuantizeLinear_Output);
	node__conv1_conv1_2_Relu_output_0_DequantizeLinear( tu2.tensor__conv1_conv1_2_Relu_output_0_QuantizeLinear_Output, &tensor__conv1_conv1_2_Relu_output_0_scale, &tensor__conv1_conv1_2_Relu_output_0_zero_point, tu3.tensor__conv1_conv1_2_Relu_output_0_DequantizeLinear_Output);
	node__conv1_conv1_3_MaxPool( tu3.tensor__conv1_conv1_2_Relu_output_0_DequantizeLinear_Output, tu2.tensor__conv1_conv1_3_MaxPool_output_0);
	node__conv1_conv1_3_MaxPool_output_0_QuantizeLinear( tu2.tensor__conv1_conv1_3_MaxPool_output_0, &tensor__conv1_conv1_2_Relu_output_0_scale, &tensor__conv1_conv1_2_Relu_output_0_zero_point, tu3.tensor__conv1_conv1_3_MaxPool_output_0_QuantizeLinear_Output);
	node__conv1_conv1_3_MaxPool_output_0_DequantizeLinear( tu3.tensor__conv1_conv1_3_MaxPool_output_0_QuantizeLinear_Output, &tensor__conv1_conv1_2_Relu_output_0_scale, &tensor__conv1_conv1_2_Relu_output_0_zero_point, tu2.tensor__conv1_conv1_3_MaxPool_output_0_DequantizeLinear_Output);
	node__conv2_conv2_0_Conv( tu2.tensor__conv1_conv1_3_MaxPool_output_0_DequantizeLinear_Output, tu5.tensor_onnx__Conv_33_DequantizeLinear_Output, tu6.tensor_onnx__Conv_34, tu3.tensor__conv2_conv2_2_Relu_output_0);
	node__conv2_conv2_2_Relu_output_0_QuantizeLinear( tu3.tensor__conv2_conv2_2_Relu_output_0, &tensor__conv2_conv2_2_Relu_output_0_scale, &tensor__conv2_conv2_2_Relu_output_0_zero_point, tu2.tensor__conv2_conv2_2_Relu_output_0_QuantizeLinear_Output);
	node__conv2_conv2_2_Relu_output_0_DequantizeLinear( tu2.tensor__conv2_conv2_2_Relu_output_0_QuantizeLinear_Output, &tensor__conv2_conv2_2_Relu_output_0_scale, &tensor__conv2_conv2_2_Relu_output_0_zero_point, tu3.tensor__conv2_conv2_2_Relu_output_0_DequantizeLinear_Output);
	node__conv2_conv2_3_GlobalAveragePool( tu3.tensor__conv2_conv2_2_Relu_output_0_DequantizeLinear_Output, tu2.tensor__conv2_conv2_3_GlobalAveragePool_output_0);
	node__conv2_conv2_3_GlobalAveragePool_output_0_QuantizeLinear( tu2.tensor__conv2_conv2_3_GlobalAveragePool_output_0, &tensor__conv2_conv2_3_GlobalAveragePool_output_0_scale, &tensor__conv2_conv2_3_GlobalAveragePool_output_0_zero_point, tu3.tensor__conv2_conv2_3_GlobalAveragePool_output_0_QuantizeLinear_Output);
	node__conv2_conv2_3_GlobalAveragePool_output_0_DequantizeLinear( tu3.tensor__conv2_conv2_3_GlobalAveragePool_output_0_QuantizeLinear_Output, &tensor__conv2_conv2_3_GlobalAveragePool_output_0_scale, &tensor__conv2_conv2_3_GlobalAveragePool_output_0_zero_point, tu2.tensor__conv2_conv2_3_GlobalAveragePool_output_0_DequantizeLinear_Output);
	node__Squeeze( tu2.tensor__conv2_conv2_3_GlobalAveragePool_output_0_DequantizeLinear_Output, tensor__Constant_output_0, tu3.tensor__Squeeze_output_0);
	node__Squeeze_output_0_QuantizeLinear( tu3.tensor__Squeeze_output_0, &tensor__conv2_conv2_3_GlobalAveragePool_output_0_scale, &tensor__conv2_conv2_3_GlobalAveragePool_output_0_zero_point, tu2.tensor__Squeeze_output_0_QuantizeLinear_Output);
	node__Squeeze_output_0_DequantizeLinear( tu2.tensor__Squeeze_output_0_QuantizeLinear_Output, &tensor__conv2_conv2_3_GlobalAveragePool_output_0_scale, &tensor__conv2_conv2_3_GlobalAveragePool_output_0_zero_point, tu3.tensor__Squeeze_output_0_DequantizeLinear_Output);
	node__fc_Gemm( tu3.tensor__Squeeze_output_0_DequantizeLinear_Output, tu1.tensor_fc_weight_DequantizeLinear_Output, tu0.tensor_fc_bias, tu2.tensor_sleep_stage_logits_QuantizeLinear_Input);
	node_sleep_stage_logits_QuantizeLinear( tu2.tensor_sleep_stage_logits_QuantizeLinear_Input, &tensor_sleep_stage_logits_scale, &tensor_sleep_stage_logits_zero_point, tu0.tensor_sleep_stage_logits_QuantizeLinear_Output);
	node_sleep_stage_logits_DequantizeLinear( tu0.tensor_sleep_stage_logits_QuantizeLinear_Output, &tensor_sleep_stage_logits_scale, &tensor_sleep_stage_logits_zero_point, tensor_sleep_stage_logits);
}
